name = "todo-preview-prod"
main = "src/index.js"
account_id = "9e21ecc38f9b90115dc0a039653bfc0c"
compatibility_date = "2025-06-09"

[[kv_namespaces]]
binding = "TODOS"
id = "59a78d7394f244b2af81ba162a55f17e"
